name: Flutter WebApp Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter pub get
      - run: flutter config --enable-web
      - run: flutter build web --release
#      - run: flutter build web --base-href "/${{ github.event.repository.name }}/"

      - run: git config user.name C0routine
      - run: git config user.email C0routine@github.com
      - run: git --work-tree build/web add --all
      - run: git commit -m "Automatic deployment by github-actions"
      - run: git push origin HEAD:gh_pages --force